//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPO_INVESTAMA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PettyCash
    {
        public string PettyCashId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Description { get; set; }
        public string AccountDetailId { get; set; }
        public string BankFacilityId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Origin { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> CheckedAt { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string ApprovalBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AccountDetail AccountDetail { get; set; }
        public virtual BankFacility BankFacility { get; set; }
    }
}
